name: 'Setup Local Artifactory'
description: 'Setup Local Artifactory'
inputs:
  RTLIC:
    description: 'Local Artifactory License.'
    required: true
  JFROG_HOME:
    description: 'JFrog Home.'
    required: false
  VERSION:
    description: 'Artifactory Version. Default is latest.'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Install Local Artifactory
      run: |
        chmod +x $GITHUB_ACTION_PATH/run-and-upload.sh
        $GITHUB_ACTION_PATH/run-and-upload.sh
      shell: bash
      env:
        RTLIC: ${{ inputs.RTLIC }}
        JFROG_HOME: ${{ inputs.JFROG_HOME }}
        VERSION: ${{ inputs.VERSION }}
